### PR TITLE
A advice in the readme

### PR DESCRIPTION
**Pull request by gartz**
When you try to install in a redmine with repositories already configured, it get errors, but is easy to fix, so I put a advice in the readme for the future users.

### CODE REVIEW

**Comment by ericpaulbishop** [comment]
I think the original error is due to the path/urls for existing git repos not getting reset correctly (to what the plugin expects) when migrating.  The solution isn't to update the readme, but to fix the migration, which I'll get around to sometime in the near future.

**Comment by gartz** [comment]
I agree with you.

Just sugest a rapid fix, because I was unable to search for the source from the problem.

**Comment by ericpaulbishop** [comment]
There is actually some code in the latest v0.4.0 version to do the url migration now, so this issue should be addressed if you are using the latest version.

**Comment by gartz** [comment]
When I migrate, was the last version already. And I have a crash that stopped the server work and I need to clean the tables again, and it start to work again...

I'm planning to migrate a redmine with lots of projects to became use this plugin, but just when I have free time to do it. Then I will track any errors and probably if this issue appears, I will reopen this ticket and put a crash report for help fix the bug.

**Pull request closed without merging**
