### PR TITLE
Non ruby repository hooks [Revisited]

### PR DESCRIPTION
**Pull request by s0undt3ch**
I've updated my non ruby repository hooks to your current master.

The reason why I'm revisiting this, is mostly because of performance issues and lower resources usage.

On the last pull request, one thing you pointed out was that, it was not good to have to manually install the hook into gitolite. This issue was fixed. A test is made to see if the post-receive hook is already installed(it won't override any existing post-receive hook). It the post-receive hook is not present, we install it and do the required procedures in order for it to populate to existing repositories. The hook won't run if it hasn't been configured(per repository). This configuration step is done automatically for new projects.

Now some visual information about my performance complaints.
I setup 2 projects with git repositories. I made sure one had your post-receive hook and the other had mine which relies on a controller to update the database.
The test was done on my laptop which is hosting everything, my dev chiliproject 1.5 install and and a dev gitolite setup, Intel Core Duo Processor T2500 2.0 GHz with 3148Gig of ram.

```
$ RAILS_ENV=production ruby projects/chiliproject/script/about
About your application's environment
Ruby version              1.8.7 (i686-linux)
RubyGems version          1.3.7
Rack version              1.0
Rails version             2.3.5
Active Record version     2.3.5
Active Resource version   2.3.5
Action Mailer version     2.3.5
Active Support version    2.3.5
Application root          /srv/chili/projects/chiliproject
Environment               production
Database adapter          sqlite3
Database schema version   20101114115359

About your Redmine plugins
Redmine Git Hosting Plugin   0.2.0
```

Now for the really interesting stuff:

```
Testing K10, ruby hook
procs -----------memory---------- ---swap-- -----io---- -system-- ----cpu----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa
 2  0   1712 148960 119780 543824    0    0    21    28  455  605 12  4 82  1
 1  0   1972  94876 118600 539724    0   52     0    95 1045 1182 47 10 42  1
 2  0   1972 115428 118612 539748    0    0     0    25  874 1529 39 12 48  1
 2  0   1972 142956 118640 539764    0    0     0    71  864 1349 41  7 50  2
 0  1   1972  94588 118656 539764    0    0     0    56  980  958 51  9 38  1
 1  0   1972  96348 118660 539804    0    0     0    60 1010 1503 39  9 51  0
 1  0   2104 133644 117732 536692    0   26     0    88  904 1514 52  9 38  0
 0  0   2104 156060 117752 536688    0    0     0    75  955  987 45  6 48  1
 1  1   2104  96328 117764 536708    0    0     0    41  794 1367 47 11 41  1
 1  0   2104 117664 117784 536744    0    0     0    50  895 1562 39 11 49  1
 1  0   2104 146060 117808 536768    0    0     0    74  861 1339 43  8 47  2
 1  0   2104  95072 117816 536768    0    0     0    42 1011 1112 50  8 40  1
 1  0   2104  97204 117836 536792    0    0     0    36  896 1520 40 11 49  1
 1  0   2104 130560 117856 536816    0    0     0   129  975 1504 40  8 47  5
 0  0   2104 152712 117876 536820    0    0     0    67 1024 1000 45  8 46  1
 2  2   2104  93592 117896 536832    0    0     0    54  912 1494 47  9 43  1
 1  0   2320 118976 116884 533260    0   43     0    75  966 1487 40 11 47  2
 1  0   2320 148472 116908 533284    0    0     0    67  929 1298 43  8 48  1
 1  0   2320  95624 116916 533284    0    0     0    41  979  946 51  9 39  1
 1  0   2320  97772 116932 533308    0    0     1    32  950 1425 39  9 51  1
 1  0   2320 131120 116960 533336    0    0     0   128  971 1532 42  9 48  1
 0  0   2320 153400 116980 533332    0    0     0    73  828 1041 58  7 35  1
 1  1   2320  93752 117000 533364    0    0     0    45  795 1358 45 11 43  1
 1  0   2320 120020 116432 530600    0    0     1    33  822 1514 39 10 51  1
 0  0   2320 153476 116456 530616    0    0     0    84  825 1349 43  7 48  2
 1  0   2320  95964 116464 530624    0    0     0    39  995  966 50  8 40  2
 1  0   2320 100924 116476 530648    0    0     0    36  962 1452 40 12 48  1
 6  0   2320 134900 116496 530672    0    0     0   125  938 1463 41  8 47  4
 0  0   2320 153592 116520 530668    0    0     0    63  742  982 48  8 41  2
 1  1   2320  94028 116528 530688    0    0     0    46  954 1387 43 10 47  1
 1  0   2432 123812 115760 528188    0   22    30    58  976 1454 39 11 48  2
 2  0   2432 154876 115780 528184    0    0     0    77 1000 1111 42  5 52  1
 1  0   2432  95880 115788 528212    0    0     0    38 1040 1295 50 11 39  1
 1  0   2432 103352 115804 528236    0    0     0    36  970 1573 39  9 52  1
 1  0   2432 145136 115832 528264    0    0     0   126  926 1362 51  8 37  4
 1  0   2432  94560 115840 528264    0    0     0    44  942 1068 51  8 41  1
 1  0   2432  96528 115860 528288    0    0     0    34 1003 1483 39  9 51  1
 1  0   2564 133296 115092 525356    1   26    20   103  946 1515 41 10 46  4
 0  0   2564 155704 115112 525372    0    0     4    77  961  937 47 12 40  2
 1  1   2564  96592 115128 525400    0    0     0   162  838 1583 45  9 42  4
 2  0   2564 119036 115144 525432    0    0     0    32  858 1462 41 11 48  1
 0  0   2564 152500 115164 525448    0    0     0   123  738 1321 42  6 51  2
 1  0   2564  95488 115172 525456    0    0     0    41  991 1066 51  8 40  1
procs -----------memory---------- ---swap-- -----io---- -system-- ----cpu----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa
 1  0   2564  99936 115192 525488    0    0     0    81  843 1481 39 10 50  1
 4  0   2564 135524 115216 525516    0    0     0    78  910 1406 42  9 45  4
 0  0   2680 156368 114292 522532    0   23     0    91  870 1134 48  8 43  2
 1  1   2680  97132 114308 522564    0    0     0    52  827 1392 54 11 34  1
 1  0   2680 122676 114324 522588    0    0     0    31  864 1610 39 11 49  1
 4  0   2680 153748 114352 522588    0    0     0   130  885 1323 45  7 46  3
 2  0   2680  98372 114368 522616    0    0     0    44  799 1524 49 10 40  1
 1  0   2680 117468 114380 522640    0    0     0    32  772 1513 41 11 48  1
 1  0   2680 147724 114392 522664    0    0     0    74  804 1332 42  7 49  2
 1  0   2680  96884 114396 522664    0    0     0    42 1022 1160 52  9 38  1
 1  0   2680  98868 114412 522692    0    0     0    34  802 1428 41 10 49  1
 1  0   2680 131852 114432 522716    0    0     0    70  916 1559 42 10 46  3
 0  0   2680 154504 114468 522716    0    0     0   121  978  936 44  7 45  4
 1  1   2680  95192 114480 522736    0    0     0    41  805 1410 47 10 43  0
 1  0   2680 116596 114488 522768    0    0     0    38  935 1638 39 10 50  1
 0  0   2688 154588 113676 520024    0    2     0    74  818 1383 53  8 38  1
 1  0   2688  96704 113680 520032    0    0     0    38  738 1111 50  8 40  2
 1  0   2688 101540 113700 520060    0    0     0    37  887 1552 41 11 47  1
 1  0   2688 134028 113720 520088    0    0     0    78  992 1558 40  9 49  2
 0  0   2856 155668 113120 516604    0   34     0   149  871 1153 50  9 40  1
 1  1   2856  95688 113132 516664    7    0    15    44 1070 1520 43  9 46  2
 1  0   2856 121852 113152 516696    0    0     0    50 1040 1481 41 11 46  2
 3  0   2856 153196 113172 516692    0    0     0    70 1071 1171 43  5 50  2
 1  0   2856  94208 113180 516720    0    0     0    38  777 1322 51 10 38  1
 1  0   2856 133172 112648 497412    6    0     6    34  882 1603 39 10 49  1
 1  0   2856 163056 112668 497440    0    0     0    77  898 1372 43  8 48  2
 1  0   2856 112464 112676 497440    0    0     0    86 1050 1123 51  8 40  1
 1  0   2856 114448 112700 497468    0    0     0    41  914 1497 51 10 38  0
Echo, commit and then push 50 times took 303.497320175 6.0699464035 per run


Testing K11, curl redmine hook
procs -----------memory---------- ---swap-- -----io---- -system-- ----cpu----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa
 2  0   2856 170584 112728 497464    0    0    21    29  455  606 13  4 81  1
 1  0   2856 166736 112772 497560    0    0     9   124 1085 2497 28 12 57  3
 2  1   2856 164164 112820 497608    0    0     1   162 1001 2383 29 12 56  2
 0  0   2856 165840 112844 497680    0    0     0   127  917 2379 28 11 58  3
 0  0   2856 164176 112880 497748    0    0     0   203 1094 2447 29 10 57  4
 1  0   2856 162640 112916 497792    0    0     0   120  956 2329 26 10 62  2
 1  0   2856 159140 112968 497832    0    0     0   128 1032 2444 30 12 55  3
 1  0   2856 156616 113008 497924    0    0     0   133 1025 2487 28 11 58  2
 2  0   2856 154404 113036 497976    0    0     0   175 1146 2454 29 11 57  3
 0  0   2856 156284 113076 498040    0    0     1   135  988 2564 29 10 58  2
 0  0   2856 155440 113108 498088    0    0     0   126 1018 2480 27 10 61  2
 2  0   2856 152128 113132 498136    0    0     0   262 1035 2462 29 11 57  2
 1  0   2856 149880 113180 498204    0    0     0   138 1059 2431 28 12 57  3
 1  1   2856 147416 113232 498248    0    0     0   167 1049 2430 29 11 56  3
 4  0   2856 148704 113272 498344    0    0     0   145 1040 2550 41 11 46  2
 0  0   2856 147224 113300 498392    0    0     0   129  978 2517 28 10 60  2
 0  0   2856 146132 113336 498444    0    0     1   119 1033 2579 28 11 58  3
 4  0   2856 141524 113368 498492    0    0     0   128 1101 2289 30 10 58  2
 1  0   2856 138952 113392 498568    0    0     0   243  998 2460 27 12 59  2
 0  0   2856 136960 113440 498616    0    0     0   182 1048 2401 30 12 56  2
 2  0   2856 138340 113468 498696    0    0     0   125 1095 2446 31 12 55  2
 0  0   2856 136652 113496 498740    0    0     0   143 1060 2460 28 10 60  1
 0  0   2856 135592 113532 498788    0    0     0   140  982 2262 28 10 59  3
 0  0   2856 134104 113564 498844    0    0     0   132  905 2312 27  9 61  3
Echo, commit and then push 50 times took 65.1094379425 1.30218875885 per run
```

Unfortunately I deleted the script which generated that cool output. I can recreate it if you wish to test it yourself.

So, how about this new approach?

Regards.

### CODE REVIEW

**Comment by ericpaulbishop** [comment]
I will need some time to look at this more closely -- I'll  get back to you on this

**Comment by s0undt3ch** [comment]
Sure, I'm now also trying to implement, per project(and respective repo) cia hook support.

**Comment by s0undt3ch** [comment]
Now, that I'm understanding more of the ruby language and the redmine/chiliproject source code, **yes** the commit support controler **is** ugly. I'm changing the code to make it better. I'll let you know when it's ready to be reviewed.

**Comment by s0undt3ch** [comment]
I've updated this branch to be up to date with your master. Here's the new stats for it:

Ruby Hook:

```
Testing 5 pushes on each of it's 2 branches with 3 commits each on ruby-hook repository
Waiting for hook to finish up 
No more hooks running. Waited 0:00:20.557862
Waiting for hook to finish up 
No more hooks running. Waited 0:00:19.681386
Waiting for hook to finish up 
No more hooks running. Waited 0:00:20.628322
Waiting for hook to finish up 
No more hooks running. Waited 0:00:19.892885
Waiting for hook to finish up 
No more hooks running. Waited 0:00:19.909806
-------------------------------------------------------------------------------
Took 101.356260061, 20.27 per push
Spent a total of 0:01:40.670261 waiting for hooks to finish.
vmstats for ruby-hook
procs -----------memory---------- ---swap-- -----io---- -system-- ----cpu----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa
 5  0  41200 463692 110000 366448    0    0   109    52    0  166  9  4 86  1
 2  0  41200 398400 110012 368796    0    0   422   119 1854 2974 51 14 25 10
 1  0  41200 395688 110028 368696    0    0     2    50 1650 3195 61 16 23  0
 1  0  41200 387380 110036 368696    0    0     0    16 1843 2515 59  7 34  0
 2  0  41200 387008 110052 368696    0    0     0    58 1899 2247 58  7 34  1
 2  0  41200 414480 110064 369312    0    0    10   173 1952 3343 38 15 46  1
 1  0  41200 383776 110080 369312    0    0     0    87 1852 2385 56 15 28  1
 1  0  41200 382016 110096 369304    0    0     0    67 1866 2208 57  7 35  1
 1  0  41200 382016 110104 369312    0    0     0   219 1842 2361 58  9 33  1
 3  0  41200 442876 110112 369340    0    0     6    97 1994 2915 46  9 45  1
 2  0  41200 384744 110128 369480    0    0     2   102 1908 2531 52 15 32  1
 1  0  41200 381148 110136 369488    0    0     0    58 1998 3708 69 18 13  0
 2  0  41200 372600 110144 369508    0    0     4    33 1940 3684 69 13 18  1
 1  0  41200 372716 110160 369508    0    0     0    20 1784 2373 57  8 35  0
 2  0  41200 399128 110172 369700    0    0     7    51 1985 3384 44 15 40  0
 1  0  41200 373344 110188 369700    0    0     0    89 1666 2364 58 13 29  1
 1  0  41200 373096 110204 369700    0    0     0   120 1466 2220 71  9 20  0
 2  0  41200 374732 110220 369692    0    0     0    22 1448 2199 57  7 35  0
 1  0  41200 434952 110228 369756    0    0     6   106 1942 3088 44 12 42  2
 1  0  41200 372708 110252 369916    0    0     2   112 1958 2485 57 13 30  1
 8  0  41200 369988 110252 369920    0    0     0    13 1856 2414 57 13 30  0
procs -----------memory---------- ---swap-- -----io---- -system-- ----cpu----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa
 6  0  41200 369888 110268 369920    0    0     0    38 1738 2188 57  6 36  0
 1  0  41200 368500 110284 369920    0    0     0    32 1584 2327 59  8 32  1
-------------------------------------------------------------------------------
```

Bash Hook:

```
Testing 5 pushes on each of it's 2 branches with 3 commits each on non-ruby-bash-hook repository
Waiting for hook to finish up 
No more hooks running. Waited 0:00:06.108906
Waiting for hook to finish up 
No more hooks running. Waited 0:00:03.735488
Waiting for hook to finish up 
No more hooks running. Waited 0:00:03.723673
Waiting for hook to finish up 
No more hooks running. Waited 0:00:03.747622
Waiting for hook to finish up 
No more hooks running. Waited 0:00:03.770438
--------------------------------------------------------------------------------
Took 21.7840089798, 4.36 per push
Spent a total of 0:00:21.086127 waiting for hooks to finish.
vmstats for non-ruby-bash-hook
procs -----------memory---------- ---swap-- -----io---- -system-- ----cpu----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa
 4  0  41200 432512 110308 369916    0    0   109    52    1  167  9  4 86  1
 1  0  41200 415060 110316 380160    0    0  2005    82 2553 4976 37 15 32 17
 2  0  41200 412804 110340 380920    0    0    66   207 1961 3476 43 13 41  3
 2  0  41200 411652 110360 381124    0    0     6   206 1852 3209 43 10 44  2
 2  0  41200 413816 110376 381184    0    0     0   102 2101 3009 49 10 39  1
 4  0  41200 411656 110396 381336    0    0     6   110 2048 3147 52 13 34  1
 1  0  41200 408280 110416 381480    0    0     7   111 1771 3184 47 11 40  2
-------------------------------------------------------------------------------
```

Python Hook:

```
Testing 5 pushes on each of it's 2 branches with 3 commits each on non-ruby-python-hook repository
Waiting for hook to finish up 
No more hooks running. Waited 0:00:04.854805
Waiting for hook to finish up 
No more hooks running. Waited 0:00:02.895187
Waiting for hook to finish up 
No more hooks running. Waited 0:00:02.879723
Waiting for hook to finish up 
No more hooks running. Waited 0:00:02.860290
Waiting for hook to finish up 
No more hooks running. Waited 0:00:02.926806
--------------------------------------------------------------------------------
Took 17.4996521473, 3.50 per push
Spent a total of 0:00:16.416811 waiting for hooks to finish.


vmstats for non-ruby-python-hook
procs -----------memory---------- ---swap-- -----io---- -system-- ----cpu----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa
 1  2  41200 410888 110440 381508    0    0   109    52    1  167  9  4 86  1
 1  0  41200 394292 111520 390156    0    0  1906   114 2485 4909 36 15 31 18
 3  0  41200 393336 111544 390600    0    0    18   250 1742 3285 46 12 39  2
 2  0  41200 391856 111564 390824    0    0     4   174 1904 3487 46 17 36  1
 4  0  41200 390152 111584 391036    0    0     4   277 1853 3308 47 12 37  3
 1  0  41200 389200 111604 391204    0    0     4   138 1797 3320 47 12 41  1
-------------------------------------------------------------------------------
```

The script used for these tests is

``` python
import os
import sys
import time
import subprocess
import timeit
import threading
import multiprocessing
from datetime import datetime, timedelta

SLEEP_BETWEEN_PUSHES = 1.0

def print_and_echo(msg):
    print msg
    p = subprocess.Popen("echo \"%s\" >> output.txt" % msg, shell=True)
    p.wait()

def run_vmstat(reponame):
    subprocess.Popen("echo \"vmstats for %s\" >> vmstats.txt" % reponame, shell=True).wait()
    subprocess.Popen("vmstat 5 >> vmstats.txt", shell=True).wait()

def kill_vmstat():
    subprocess.Popen("echo \"%s\\n\\n\" >> vmstats.txt" % ('-'*79), shell=True).wait()
    p = subprocess.Popen("kill -KILL $(ps aux | grep vmstat | grep -v grep | awk '{print $2}')", shell=True)
    p.wait()

def wait_for_hooks_to_finish():
    global WAITING_FOR_HOOKS
    start = datetime.utcnow()
    print_and_echo("Waiting for hook to finish up ")
    counter = 3
    # Some time for the hook to start
    time.sleep(1)
    while True:
      if not counter:
        break
      p = subprocess.Popen(
        "ps aux | grep hooks/post-receive | grep -v grep", shell=True, stdout=subprocess.PIPE
      )
      p.wait()
      output = p.stdout.read()
      if output:
        sys.stdout.write('.')
        sys.stdout.flush()
        counter = 3
        time.sleep(0.25)
      else:
        counter -= 1
    finish = datetime.utcnow()
    print
    waiting = finish - start
    WAITING_FOR_HOOKS += waiting
    print_and_echo("No more hooks running. Waited %s" % waiting)

def test_repo(reponame, num_commits=1):
    repopath = os.path.join('/home/vampas/projects/RedmineGitHosting/.test-repos', reponame)
    subprocess.Popen(["git", "checkout", "foo"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=repopath).wait()
#    subprocess.Popen(["git", "branch"], cwd=repopath).wait()
    commits = 0
    while True:
        p = subprocess.Popen(
          "echo 1 >> readme.txt && git commit -am \"$(date)\"",
          cwd=repopath, shell=True,
          stdout=subprocess.PIPE,
#                                       stderr=subprocess.PIPE
        )
        p.wait()
        commits += 1
        if commits >= num_commits:
          break

    subprocess.Popen(["git", "checkout", "master"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=repopath).wait()
#    subprocess.Popen(["git", "branch"], cwd=repopath).wait()
    commits = 0
    while commits <= num_commits:
        p = subprocess.Popen(
          "echo 1 >> readme.txt && git commit -am \"$(date)\"",
          cwd=repopath, shell=True,
          stdout=subprocess.PIPE,
#                                       stderr=subprocess.PIPE
        )
        p.wait()
        commits += 1

    p = subprocess.Popen(
        "git push", cwd=repopath, shell=True,
        stdout=subprocess.PIPE,
#                               stderr=subprocess.PIPE
    )
    time.sleep(SLEEP_BETWEEN_PUSHES)
    wait_for_hooks_to_finish()
    time.sleep(SLEEP_BETWEEN_PUSHES)

if __name__ == '__main__':
    NUM_COMMITS = 3
    NUM_PUSHES = 50
    NUM_PUSHES=5

    global WAITING_FOR_HOOKS
    WAITING_FOR_HOOKS = timedelta(seconds=0)

    subprocess.Popen("echo > vmstats.txt", shell=True).wait()
    subprocess.Popen("echo > output.txt", shell=True).wait()

    time.sleep(3)
    #stats = threading.Thread(target=run_vmstat)
    reponame = "ruby-hook"
    stats = multiprocessing.Process(target=run_vmstat, args=(reponame,))
    stats.start()
    print_and_echo("\nTesting %s pushes on each of it's 2 branches with %s commits each on %s repository" % (NUM_PUSHES, NUM_COMMITS, reponame))

    t = timeit.Timer("test_repo('%s', %d)" % (reponame, NUM_COMMITS), "from __main__ import test_repo")
    n = t.timeit(NUM_PUSHES)
    total = n - (NUM_PUSHES * SLEEP_BETWEEN_PUSHES * 2)
    print_and_echo("-" * 79)
    print_and_echo("Took %s, %.2f per push" % (total, (total / NUM_PUSHES)))
    print_and_echo("Spent a total of %s waiting for hooks to finish." % WAITING_FOR_HOOKS)
    WAITING_FOR_HOOKS = timedelta(seconds=0)
    stats.join(0)
    kill_vmstat()
    print
#    wait_for_hooks_to_finish()


    time.sleep(5)
    reponame = "non-ruby-bash-hook"
    #stats = threading.Thread(target=run_vmstat)
    stats = multiprocessing.Process(target=run_vmstat, args=(reponame,))
    stats.start()

    print_and_echo("\nTesting %s pushes on each of it's 2 branches with %s commits each on %s repository" % (NUM_PUSHES, NUM_COMMITS, reponame))

    t = timeit.Timer("test_repo('%s', %d)" % (reponame, NUM_COMMITS), "from __main__ import test_repo")
    n = t.timeit(NUM_PUSHES)
    total = n - (NUM_PUSHES * SLEEP_BETWEEN_PUSHES * 2)
    print_and_echo("-" * 80)
    print_and_echo("Took %s, %.2f per push" % (total, (total / NUM_PUSHES)))
    print_and_echo("Spent a total of %s waiting for hooks to finish." % WAITING_FOR_HOOKS)
    WAITING_FOR_HOOKS = timedelta(seconds=0)
    stats.join(0)
    kill_vmstat()
    print
#    wait_for_hooks_to_finish()


    time.sleep(5)
    reponame = "non-ruby-python-hook"
    #stats = threading.Thread(target=run_vmstat)
    stats = multiprocessing.Process(target=run_vmstat, args=(reponame,))
    stats.start()
    print_and_echo("\nTesting %s pushes on each of it's 2 branches with %s commits each on %s repository" % (NUM_PUSHES, NUM_COMMITS, reponame))
    t = timeit.Timer("test_repo('%s', %d)" % (reponame, NUM_COMMITS), "from __main__ import test_repo")
    n = t.timeit(NUM_PUSHES)
    total = n - (NUM_PUSHES * SLEEP_BETWEEN_PUSHES * 2)
    print_and_echo("-" * 80)
    print_and_echo("Took %s, %.2f per push" % (total, (total / NUM_PUSHES)))
    print_and_echo("Spent a total of %s waiting for hooks to finish." % WAITING_FOR_HOOKS)
    WAITING_FOR_HOOKS = timedelta(seconds=0)
    stats.join(0)
    kill_vmstat()
    print
#    wait_for_hooks_to_finish()

    time.sleep(1)
    os._exit(0)
```

As you might notice from the stats pointed above, my approach is way faster, and less resources are required. I even added a python version of the post-receive hook which is even faster than the bash version.

Please review the code changes required, and if anything else isn't to your taste, lemme know and I'll change it so that this can be included in your master branch of this wonderful plugin.

**Comment by ericpaulbishop** [comment]
I agree with you that the plugin should be updated so that the hooks are set in the gitolite admin repo, not directly in the git user home directly.  

I also agree with you that we should try to improve the speed of the post-receive hook.  However... I disagree on how this should be done.  I think the best strategy here is to use the ruby command, but run it in the background, asynchronously.  This should fix the issue with how long it takes the hook to run, and I don't think the resource consumption is that severe an issue given that the hook does not that long to run (though longer than we want to wait for in the post-receive hook)

Here is why I'd like to keep the ruby portion of the hook: The new git caching functionality, which massively speeds up the load time of the git repo, requires that the cached commands for a given repo are cleared when the post-receive hook is called.  To do this, the ruby update script needs to be run.

**Comment by s0undt3ch** [comment]
Do notice that I also clear the caches when my hooks are called

**Comment by s0undt3ch** [comment]
See here https://github.com/s0undt3ch/redmine_git_hosting/blob/post-receive-hook/app/controllers/gitolite_hooks_controller.rb#L22-L30

**Comment by s0undt3ch** [comment]
The reason why I started working on this is because my virtual server resources are already being streched to the maximum, hence why I moved from several trac instances to a single redmine instance, to lower my resources consumption. It did lower, but not enough and I narrowed it down to this plugin and it's update hook, and other non cached call's in it.

**Comment by ericpaulbishop** [comment]
Ahhhh... I see, you added a new controller as well.  That suddenly makes a lot more sense.

**Comment by s0undt3ch** [comment]
Yep, way cleaner, from my non-ruby-coder point of view.

**Comment by s0undt3ch** [comment]
I'm currently working on an issue where the git user is not the same as the web user while installing the hook, but this is a minor glitch. I made my dev setup run both the repos and the chiliproject under the same user account :\

**Comment by s0undt3ch** [comment]
Ok, glitches solved.

**Comment by ericpaulbishop** [comment]
quick question: in the source you have commented that the python version of the hook executes faster, do you know why this is the case?

**Comment by s0undt3ch** [comment]
I think it might be because of iterating through what's fed to the script's `stdin` and how it handles it.

See [here](https://github.com/s0undt3ch/redmine_git_hosting/blob/post-receive-hook/contrib/hooks/post-receive.redmine_gitolite#L101-103).

Although that part can be commented out, I left it there because the next stage on my mind is to provide CIA notifications per project, and those notifications need the info that's iterated on the script.

**Comment by s0undt3ch** [comment]
I've added several comments to the commits on the branch you created to get my work into your plugin.

If redmine/chiliproject has a setting "Enable WS for repository management" which then generates a key, this already exists, why are you creating a table just to store the plugin's api key, which in turn made you change the way the hook accesses the right controller, which should only accept POST requests, a GET request should be an error.

**Comment by ericpaulbishop** [comment]
There are two very good reasons why I created a new parameter beyond what already exists:

(1) The key needs to be generated and set AUTOMATICALLY, without the possibility of it every being changed by a human being.  The current mechanism requires that someone activate it and generate the key.  That is unacceptable -- there is no reason for human involvement in in this process.  So, I created a new parameter that does essentially the same thing.  I could set the sys_api_key parameter automatically... but the controls are still there for someone to come along and change it, which I want to prohibit.  Because of the way settings work in ChiliProject/Redmine, it's not possible to just use a setting to save an automatically generated value.  If you know of a way to do that, please let me know and I'll use that instead.

(2) The second reason is security.  I haven't implemented this yet, but the actual key shouldn't be what is sent.  Instead there should be a randomly generated salt and the hashed key with this salt.  That way the actual key is never transmitted.  It would be a pain to patch this into the existing system, especially if people are already using it the way it is, but I would prefer to do it this way for the new system that the typical git hooks use.

**Comment by s0undt3ch** [comment]
The idea was to whenever the api key changed, repo configs would be updated too. Ok, now I get what you're trying to achieve.

Pull request #49 is based on the work I had done on this branch, I'll try to keep it up to date to your "implementation" branch so that a future merge will be simpler.

**Comment by s0undt3ch** [comment]
The branch used for this pull request is now up to date with your new features branch.
I've added some enhancements to what was done previously.

**Comment by s0undt3ch** [comment]
dam still not working

**Comment by ghost** [comment]
How long until this is in master? I could definitely use a post-receive hook solution, seeing as I don't really have any other way to update the repository (autofetch doesn't work, and I can't use my own custom hook to call sys/fetch_changesets since it won't work for this for some reason).

Also please checkout my issue #59. I'd appreciate it be implemented (unless you already have!), and it _might_ be right up your alley as well. When I had installed this plugin, that option was disabled by default on the project, and I had no way to enable it so I could view changesets (except via phpMyAdmin), and once I did, updating using my hook or using autofetch didn't work. :/

**Comment by s0undt3ch** [comment]
@ Eric:
With the commit above, we achieve what you wished. Each repository will have a base64 encoded AES signed key which will be used to "authenticate" the hook script. This is per repository.

@ Roejames12:
I think Eric should be pretty busy, and everything needs to be like _he_ think's it should be. So, your best option is wait until it actually reaches master or start using the _unstable_ branch.

**Comment by ericpaulbishop** [comment]
Already merged in new_hook_handling branch

**Pull request closed without merging**
