### PR TITLE
Extended features

### PR DESCRIPTION
**Pull request by rchady**
I didn't do my development on a clone of my fork so everything is rolled together in a single branch.  The main changes are:
- Allow setting a config file to use rather than gitolite.conf
- Allow setting the gitolite admin user, this was needed in case you don't use gitolite.conf, you can't parse out the admin user.
- Allow the ability to set gitolite id prefix/suffixes

The only caveat is if you use a separate file for your managed repositories, you need to provide instructions that 'include "managed_file.conf"' be added to gitolite.conf one time so the repos all get pulled in.

### CODE REVIEW

**Comment by ericpaulbishop** [comment]
I've now merged this into a new branch (new_config_handling), which will be merged into master after some testing.

**Comment by rchady** [comment]
I will be using this actively so please let me know of any issues you come across.  The only other thing I am considering doing is making it possible to cluster all the managed repositories underneath a configurable top-level folder.

**Comment by rchady** [comment]
I've updated my extended_features branch with support for specifying a top level folder inside gitolite.  I'm not sure how to issue a pull request for only the one commit, but if you pull from that branch it is commit 1a2d2c98d620821a0149c24160acbe318601eb62.

**Comment by rchady** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hello,

I was curious whether or not you had any things in place for supporting the 'config' lines that gitolite supports per repo?  Looking to use it for automatically defining some hooks values per repo, but as far as I can tell your plugin strips the 'config' entries.
- --Robert

On Oct 6, 2011, at 1:42 PM, Eric Bishop wrote:

> I've now merged this into a new branch (new_config_handling), which will be merged into master after some testing.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ericpaulbishop/redmine_git_hosting/pull/99#issuecomment-2313448

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.9 (Darwin)

iEYEARECAAYFAk7KmQAACgkQ8Eouv0ZUNqXm/gCgqgjNQB2JafH4s8tUbFq50XmI
2iwAmQEVZSPo9LRZhqMp2nu8rqMER0Gm
=L+jX
-----END PGP SIGNATURE-----

**Pull request closed without merging**
